### ISSUE TITLE
Fine-tune llm2-7B Model on OpenFn Custom Datasets

### ISSUE THREAD

**Issue by ismailousa** [OpenFn/gen#22]
**GitHub Issue Title:** Fine-tune llm2-7B Model on OpenFn Custom Datasets

**Description:**
This issue focuses on the fine-tuning of the llm2-7B language model using custom datasets from OpenFn. The aim is to adapt the model to the specific syntax and patterns found in OpenFn datasets.

**Steps:**
1. **Dataset Preparation:**
    - Identify and gather the OpenFn custom datasets that will be used for fine-tuning.
    - Ensure the datasets are properly cleaned and contain relevant code examples with instruction signatures.

2. **Model Configuration:**
    - Choose the llm2-7B model as the base model for fine-tuning.
    - Configure the model parameters, including any specific settings required for the custom datasets.

3. **Fine-tuning Process:**
    - Implement a fine-tuning script using Hugging Face's Transformers library.
    - Fine-tune the llm2-7B model on the OpenFn custom datasets, allowing the model to learn the syntax and patterns present in the data.
    - Monitor the training process, and adjust hyperparameters if necessary to achieve optimal results.

4. **Metrics Evaluation:**
    - Evaluate the performance of the fine-tuned model on validation datasets.
    - Calculate and report relevant metrics such as F1 score, precision, and recall.

5. **Results Analysis:**
    - Analyze the generated signatures and code snippets to ensure they align with the expected syntax and patterns in OpenFn datasets.
    - Identify any potential issues or areas for improvement.

6. **Documentation:**
    - Document the fine-tuning process, including hyperparameters, in a README or relevant documentation.
    - Provide instructions for reproducing the fine-tuning process.

7. **Testing:**
    - Test the fine-tuned model on a separate set of OpenFn datasets to verify its generalization capabilities.

**Definition of Done:**
- The llm2-7B model has been successfully fine-tuned on OpenFn custom datasets.
- The fine-tuned model demonstrates satisfactory performance on validation datasets, as measured by relevant metrics.
- Generated code snippets and instruction signatures align with the expected syntax and patterns in OpenFn datasets.
- Documentation is updated to reflect the fine-tuning process, including hyperparameters and instructions for reproduction.
- The fine-tuned model passes testing on additional OpenFn datasets, demonstrating its generalization capabilities.

Note: It's essential to continuously communicate and collaborate with the team during the process, seeking feedback and making adjustments as needed.

**Comment by josephjclark** [comment]
Here's an example: is the jsdoc here a useful prompt/input or would you like a natural language prompt too?

```
/**
 * Tag members with a particular tag
 * @example
 * tagMembers((state) => ({
 *   listId: "someId", // All Subscribers list
 *   tagId: "someTag", // User tag
 *   members: state.response.body.rows.map((u) => u.email),
 * }));
 * @example
 * tagMembers((state) => ({
 *   listId: "someId",
 *   tagId: "someTag",
 *   members: state.response.body.rows
 *     .filter((u) => u.allow_other_emails)
 *     .map((u) => u.email),
 * }));
 * @function
 * @param {object} params - a tagId, members, and a list
 * @param {function} [callback] - Optional callback to handle the response
 * @returns {Operation}
 */
export function tagMembers(params, callback = s => s) {
  return state => {
    const [resolvedParams] = expandReferences(state, params);
    const { listId, tagId, members } = resolvedParams;

    return state.client.lists
      .batchSegmentMembers({ members_to_add: members }, listId, tagId)
      .then(response => handleResponse(response, state, callback));
  };
}
```

**Comment by josephjclark** [comment]
Oh maybe that's a bad example because it's client based, not request based

**Comment by josephjclark** [comment]
An example from msgraph (I don't know if this has an openapi spec but if it does, it'll be a monster - it's a HUGE API). It's request-based so that's good.
```
/**
 * Create some resource in msgraph
 * @public
 * @example
 * create("applications", {"displayName": "My App"})
 * @function
 * @param {string} resource - The type of entity that will be created
 * @param {object} data - The data to create the new resource
 * @param {function} callback - An optional callback function
 * @returns {Operation}
 */
export function create(resource, data, callback) {
  return state => {
    const [resolvedResource, resolvedData] = expandReferences(
      state,
      resource,
      data
    );

    const { accessToken, apiVersion } = state.configuration;

    const url = setUrl({ apiVersion, resolvedResource });

    const options = {
      accessToken,
      body: JSON.stringify(resolvedData),
      method: 'POST',
    };

    return request(url, options).then(response =>
      handleResponse(response, state, callback)
    );
  };
}
```

**Comment by josephjclark** [comment]
Another example from `dhis2` - another super complex API. Again this is request based.

```
/**
 * Update data. A generic helper function to update a resource object of any type.
 * Updating an object requires to send `all required fields` or the `full body`
 * @public
 * @function
 * @param {string} resourceType - The type of resource to be updated. E.g. `dataElements`, `organisationUnits`, etc.
 * @param {string} path - The `id` or `path` to the `object` to be updated. E.g. `FTRrcoaog83` or `FTRrcoaog83/{collection-name}/{object-id}`
 * @param {Object} data - Data to update. It requires to send `all required fields` or the `full body`. If you want `partial updates`, use `patch` operation.
 * @param {Object} [options] - Optional `options` to define URL parameters via params (E.g. `filter`, `dimension` and other import parameters), request config (E.g. `auth`) and the DHIS2 apiVersion.
 * @param {function} [callback]  - Optional callback to handle the response
 * @returns {Operation}
 * @example <caption>a program</caption>
 * update('programs', 'qAZJCrNJK8H', {
 *   name: '14e1aa02c3f0a31618e096f2c6d03bed',
 *   shortName: '14e1aa02',
 *   programType: 'WITHOUT_REGISTRATION',
 * });
 */
export function update(
  resourceType,
  path,
  data,
  options = {},
  callback = false
) {
  return state => {
    console.log(`Preparing update operation...`);

    const resolvedResourceType = expandReferences(resourceType)(state);
    const resolvedPath = expandReferences(path)(state);
    const resolvedData = expandReferences(data)(state);
    const resolvedOptions = expandReferences(options)(state);

    const { params, requestConfig } = resolvedOptions;
    const { configuration } = state;

    return request(configuration, {
      method: 'put',
      url: generateUrl(
        configuration,
        resolvedOptions,
        resolvedResourceType,
        path
      ),
      params,
      data: resolvedData,
      ...requestConfig,
    }).then(result => {
      console.log(`Updated ${resolvedResourceType} at ${resolvedPath}`);
      return handleResponse(result, state, callback);
    });
  };
}
```

**Comment by ismailousa** [comment]
Llama2 has been discarded. See services/openfn_llama/ for more info on the model
